/**
 * SWIFT MT112 — Status of Stop Payment.
 *
 * <p>Response to stop payment
 *
 * <p>Category: 1<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt112;
