/**
 * SWIFT MT760 — Issue of a Demand Guarantee / Standby Letter of Credit.
 *
 * <p>Bank guarantee issuance
 *
 * <p>Category: 7<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt760;
