/**
 * SWIFT MT900 — Confirmation of Debit.
 *
 * <p>Debit confirmation
 *
 * <p>Category: 9<br>
 * Payment: false<br>
 * Statement: true<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt900;
