/**
 * DigitalOnlyChecking delivered via the In-Branch Kiosk channel (KIOSK).
 *
 * <p>Channel type: PHYSICAL<br>
 * Device class: TOUCHSCREEN<br>
 * Auth strength: CARD_PIN<br>
 * Target latency: 400ms
 *
 * <p>Generated by {@code ChannelVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.channel.digitalonlychecking.kiosk;
