/**
 * NACHA SEC code MTE — Machine Transfer Entry.
 *
 * <p>ATM cash withdrawal entry<br>
 * Use case: ATM network entry<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: true<br>
 * Allows return: false
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.mte;
