/**
 * SWIFT MT104 — Direct Debit Request.
 *
 * <p>Direct debit collection request
 *
 * <p>Category: 1<br>
 * Payment: true<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt104;
