/**
 * StandardSavings regional fork for North Dakota (ND), MIDWEST.
 *
 * <p>Generated by {@code RegionalForkGenerator}. State-level
 * overrides include Reg DD disclosure variations, escheatment rules,
 * state tax withholding for retirement products, and FDIC regional
 * examiner assignment (KANSAS_CITY).
 */
package com.omnibank.regional.standardsavings.nd;
