package com.omnibank.channel.traditionalira.call_center;

import java.time.Duration;
import java.util.Locale;
import java.util.Map;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Auto-generated channel-scenario tests for the TraditionalIraCallcenter channel
 * fork. Generated by
 * {@code com.aibench.codegen.ChannelScenarioTestGenerator}
 * using only the public APIs already present.
 *
 * <p>Coverage: session-timeout invariants, auth-factor sanity,
 * feature-gating consistency, multi-locale UI copy, error-code
 * translation fallbacks, event tracker accumulation.
 */
class TraditionalIraCallcenterScenarioMatrixTest {

    @Test
    void session_idle_timeout_does_not_exceed_absolute_timeout() {
        var cfg = new TraditionalIraCallcenterSessionConfig();
        assertThat(cfg.idleTimeout()).isLessThanOrEqualTo(cfg.absoluteTimeout());
    }

    @Test
    void session_refresh_interval_is_shorter_than_idle_timeout() {
        var cfg = new TraditionalIraCallcenterSessionConfig();
        assertThat(cfg.refreshInterval()).isLessThan(cfg.idleTimeout());
    }

    @Test
    void session_supports_at_least_one_concurrent_session() {
        var cfg = new TraditionalIraCallcenterSessionConfig();
        assertThat(cfg.maxConcurrentSessions()).isGreaterThanOrEqualTo(1);
    }

    @Test
    void session_target_latency_is_realistic() {
        var cfg = new TraditionalIraCallcenterSessionConfig();
        assertThat(cfg.targetLatencyMs()).isBetween(50, 30_000);
    }

    @Test
    void exceeds_latency_target_at_double_the_target() {
        var cfg = new TraditionalIraCallcenterSessionConfig();
        assertThat(cfg.exceedsLatencyTarget(cfg.targetLatencyMs() * 2L)).isTrue();
    }

    @Test
    void exceeds_latency_target_at_one_below_is_false() {
        var cfg = new TraditionalIraCallcenterSessionConfig();
        assertThat(cfg.exceedsLatencyTarget(cfg.targetLatencyMs() - 1L)).isFalse();
    }

    @Test
    void device_class_is_named() {
        var cfg = new TraditionalIraCallcenterSessionConfig();
        assertThat(cfg.deviceClass()).isNotBlank();
    }

    @Test
    void auth_policy_password_is_among_base_factors_or_strong_alternative() {
        var auth = new TraditionalIraCallcenterAuthenticationPolicy();
        assertThat(auth.baseFactors()).isNotEmpty();
        assertThat(auth.maxFailedAttempts()).isBetween(1, 20);
    }

    @Test
    void auth_policy_step_up_triggers_have_required_factors() {
        var auth = new TraditionalIraCallcenterAuthenticationPolicy();
        for (var trigger : auth.stepUpTriggers()) {
            assertThat(trigger.requiredFactors()).isNotEmpty();
            assertThat(trigger.reason()).isNotBlank();
        }
    }

    @Test
    void auth_strength_label_is_not_blank() {
        var auth = new TraditionalIraCallcenterAuthenticationPolicy();
        assertThat(auth.authStrength()).isNotBlank();
    }

    @Test
    void feature_gating_view_balance_always_available() {
        var fg = new TraditionalIraCallcenterFeatureGating();
        assertThat(fg.isFeatureAvailable("VIEW_BALANCE")).isTrue();
    }

    @Test
    void feature_gating_unknown_feature_unavailable() {
        var fg = new TraditionalIraCallcenterFeatureGating();
        assertThat(fg.isFeatureAvailable("INTERPLANETARY_TRANSFER")).isFalse();
    }

    @Test
    void feature_gating_available_features_is_nonempty() {
        var fg = new TraditionalIraCallcenterFeatureGating();
        assertThat(fg.availableFeatures()).isNotEmpty();
    }

    @Test
    void feature_gating_predicates_consistent_with_set_membership() {
        var fg = new TraditionalIraCallcenterFeatureGating();
        for (var feature : fg.availableFeatures()) {
            assertThat(fg.isFeatureAvailable(feature))
                    .as("feature " + feature)
                    .isTrue();
        }
    }

    @Test
    void ui_copy_welcome_renders_in_english_and_spanish() {
        var ui = new TraditionalIraCallcenterUiCopy();
        assertThat(ui.welcomeHeadline(Locale.ENGLISH)).isNotBlank();
        assertThat(ui.welcomeHeadline(new Locale("es"))).isNotBlank();
    }

    @Test
    void ui_copy_confirm_deposit_prompt_is_locale_aware() {
        var ui = new TraditionalIraCallcenterUiCopy();
        assertThat(ui.confirmDepositPrompt(Locale.ENGLISH)).isNotBlank();
    }

    @Test
    void ui_copy_recommended_max_chars_is_positive() {
        var ui = new TraditionalIraCallcenterUiCopy();
        assertThat(ui.recommendedCopyMaxChars()).isGreaterThan(0);
    }

    @Test
    void ui_copy_error_message_map_returns_a_map() {
        var ui = new TraditionalIraCallcenterUiCopy();
        Map<String, String> map = ui.errorMessageMap(Locale.ENGLISH);
        assertThat(map).isNotNull();
    }

    @Test
    void error_translator_fallback_returned_for_unknown_codes() {
        var et = new TraditionalIraCallcenterErrorTranslator();
        assertThat(et.translateWithFallback("NOPE_NOT_A_CODE", "fallback"))
                .isEqualTo("fallback");
    }

    @Test
    void event_tracker_records_and_counts() {
        var tracker = new TraditionalIraCallcenterEventTracker();
        tracker.track("page.view");
        tracker.track("page.view");
        tracker.track("button.click");
        assertThat(tracker.count("page.view")).isEqualTo(2);
        assertThat(tracker.totalEvents()).isEqualTo(3);
        tracker.reset();
        assertThat(tracker.totalEvents()).isZero();
    }
}
