/**
 * SWIFT MT101 — Request for Transfer.
 *
 * <p>Customer initiated batch transfer request
 *
 * <p>Category: 1<br>
 * Payment: true<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt101;
