/**
 * BasicChecking regional fork for Illinois (IL), MIDWEST.
 *
 * <p>Generated by {@code RegionalForkGenerator}. State-level
 * overrides include Reg DD disclosure variations, escheatment rules,
 * state tax withholding for retirement products, and FDIC regional
 * examiner assignment (CHICAGO).
 */
package com.omnibank.regional.basicchecking.il;
