/**
 * StandardSavings regional fork for South Carolina (SC), SOUTH.
 *
 * <p>Generated by {@code RegionalForkGenerator}. State-level
 * overrides include Reg DD disclosure variations, escheatment rules,
 * state tax withholding for retirement products, and FDIC regional
 * examiner assignment (ATLANTA).
 */
package com.omnibank.regional.standardsavings.sc;
