/**
 * NACHA SEC code POS — Point-of-Sale Entry.
 *
 * <p>ATM/POS debit<br>
 * Use case: ATM/POS<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: true<br>
 * Allows return: false
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.pos;
