/**
 * NACHA SEC code ATX — Acknowledgement With Addenda.
 *
 * <p>Corporate ack with addenda<br>
 * Use case: Corporate ack<br>
 * Consumer/Corporate: CORPORATE<br>
 * Requires authorization: false<br>
 * Allows return: false
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.atx;
