/**
 * StandardSavings regional fork for Montana (MT), WEST.
 *
 * <p>Generated by {@code RegionalForkGenerator}. State-level
 * overrides include Reg DD disclosure variations, escheatment rules,
 * state tax withholding for retirement products, and FDIC regional
 * examiner assignment (SAN_FRANCISCO).
 */
package com.omnibank.regional.standardsavings.mt;
