/**
 * NACHA SEC code PBR — Consumer Cross-Border Payment.
 *
 * <p>Foreign consumer payment<br>
 * Use case: Inbound foreign consumer<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: true<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.pbr;
