/**
 * HighYieldSavings delivered via the ATM Network channel (ATM).
 *
 * <p>Channel type: PHYSICAL<br>
 * Device class: ATM<br>
 * Auth strength: CARD_PIN<br>
 * Target latency: 200ms
 *
 * <p>Generated by {@code ChannelVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.channel.highyieldsavings.atm;
