package com.omnibank.nacha.ack;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Auto-generated scenario tests for the ACK NACHA SEC-code
 * processor. Generated by
 * {@code com.aibench.codegen.NachaScenarioTestGenerator}.
 *
 * <p>Coverage: SEC-code identity, batch counters, entry validation
 * (routing length / amount sign), R-code catalog completeness,
 * return-window enforcement, authorization-signature flags.
 */
class ACKScenarioMatrixTest {

    private final ACKProcessor processor = new ACKProcessor();
    private final ACKReturnProcessor returnProcessor = new ACKReturnProcessor();
    private final ACKAuthorizationCheck authCheck = new ACKAuthorizationCheck();

    @Test
    void sec_code_is_short_and_uppercase() {
        var sec = processor.secCode();
        assertThat(sec).isNotBlank();
        assertThat(sec.length()).isBetween(2, 4);
        assertThat(sec).isEqualTo(sec.toUpperCase());
    }

    @Test
    void classification_is_consumer_or_corporate() {
        assertThat(processor.classification())
                .isIn("CONSUMER", "CORPORATE");
    }

    @Test
    void empty_batch_yields_empty_accepted_and_rejected() {
        var result = processor.processBatch(List.of(), Map.of());
        assertThat(result.accepted()).isEmpty();
        assertThat(result.rejected()).isEmpty();
        assertThat(result.rejectionReasons()).isEmpty();
    }

    @Test
    void batch_counter_increments_per_invocation() {
        long before = processor.batchesProcessed();
        processor.processBatch(List.of(), Map.of());
        processor.processBatch(List.of(), Map.of());
        assertThat(processor.batchesProcessed() - before).isEqualTo(2);
    }

    @Test
    void process_batch_null_entries_throws_npe() {
        assertThatThrownBy(() ->
                processor.processBatch(null, Map.of()))
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void process_batch_handles_null_auth_map() {
        var result = processor.processBatch(List.of(), null);
        assertThat(result).isNotNull();
    }

    @Test
    void entry_rejects_short_routing_number() {
        assertThatThrownBy(() -> new ACKEntry(
                "22", "12345", "0123456789",
                BigDecimal.TEN, "ID1", "Name", "",
                LocalDate.of(2026, 4, 19), "T1", null))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("9");
    }

    @Test
    void entry_rejects_negative_amount() {
        assertThatThrownBy(() -> new ACKEntry(
                "22", "012345678", "0123456789",
                new BigDecimal("-1"), "ID1", "Name", "",
                LocalDate.of(2026, 4, 19), "T1", null))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("non-negative");
    }

    @Test
    void entry_rejects_null_routing_number() {
        assertThatThrownBy(() -> new ACKEntry(
                "22", null, "0123456789",
                BigDecimal.TEN, "ID1", "Name", "",
                LocalDate.of(2026, 4, 19), "T1", null))
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void entry_rejects_null_amount() {
        assertThatThrownBy(() -> new ACKEntry(
                "22", "012345678", "0123456789",
                null, "ID1", "Name", "",
                LocalDate.of(2026, 4, 19), "T1", null))
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void entry_zero_amount_is_accepted() {
        // NACHA allows pre-notification zero-dollar entries.
        var entry = new ACKEntry(
                "22", "012345678", "0123456789",
                BigDecimal.ZERO, "ID1", "Name", "",
                LocalDate.of(2026, 4, 19), "T1", null);
        assertThat(entry.amount().signum()).isZero();
    }

    @Test
    void entry_sec_code_matches_processor() {
        var entry = new ACKEntry(
                "22", "012345678", "0123456789",
                BigDecimal.TEN, "ID1", "Name", "",
                LocalDate.of(2026, 4, 19), "T1", null);
        assertThat(entry.secCode()).isEqualTo(processor.secCode());
    }

    @Test
    void entry_consumer_corporate_predicates_are_mutually_exclusive() {
        var entry = new ACKEntry(
                "22", "012345678", "0123456789",
                BigDecimal.TEN, "ID1", "Name", "",
                LocalDate.of(2026, 4, 19), "T1", null);
        assertThat(entry.isConsumer() && entry.isCorporate()).isFalse();
    }

    @Test
    void return_processor_publishes_standard_r_code_set() {
        assertThat(ACKReturnProcessor.STANDARD_R_CODES)
                .isNotEmpty()
                .contains("R01");
    }

    @Test
    void return_window_days_is_non_negative() {
        assertThat(returnProcessor.returnWindowDays())
                .isGreaterThanOrEqualTo(0);
    }

    @Test
    void return_processor_rejects_unknown_rcode() {
        var outcome = returnProcessor.process(
                new ACKReturnProcessor.ReturnEntry(
                        "Z99", "T0001", LocalDate.of(2026, 4, 1),
                        LocalDate.of(2026, 4, 5), "test"));
        assertThat(outcome.accepted()).isFalse();
        assertThat(outcome.disposition()).isNotBlank();
    }

    @Test
    void authorization_signature_flags_are_booleans() {
        // Just call them to ensure no NPE; values vary by SEC code.
        boolean wet = authCheck.requiresWetSignature();
        boolean electronic = authCheck.electronicSignatureAcceptable();
        assertThat(wet).isIn(true, false);
        assertThat(electronic).isIn(true, false);
    }

    @Test
    void authorization_verify_returns_outcome_consistent_with_violations() {
        var entry = new ACKEntry(
                "22", "012345678", "0123456789",
                BigDecimal.TEN, "ID1", "Name", "",
                LocalDate.of(2026, 4, 19), "T1", null);
        var outcome = authCheck.verify(entry, null);
        assertThat(outcome).isNotNull();
        assertThat(outcome.ok()).isEqualTo(outcome.violations().isEmpty());
    }
}
