/**
 * SWIFT MT111 — Request for Stop Payment.
 *
 * <p>Stop payment request
 *
 * <p>Category: 1<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt111;
