/**
 * SWIFT MT754 — Advice of Payment/Acceptance/Negotiation.
 *
 * <p>Payment advice under LC
 *
 * <p>Category: 7<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt754;
