/**
 * NACHA SEC code RCK — Represented Check Entry.
 *
 * <p>Returned check re-presented<br>
 * Use case: NSF re-presentation<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: false<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.rck;
