/**
 * BasicChecking regional fork for Virginia (VA), SOUTH.
 *
 * <p>Generated by {@code RegionalForkGenerator}. State-level
 * overrides include Reg DD disclosure variations, escheatment rules,
 * state tax withholding for retirement products, and FDIC regional
 * examiner assignment (ATLANTA).
 */
package com.omnibank.regional.basicchecking.va;
