/**
 * NACHA SEC code IAT — International ACH Transaction.
 *
 * <p>Cross-border ACH<br>
 * Use case: International funds transfer<br>
 * Consumer/Corporate: CORPORATE<br>
 * Requires authorization: true<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.iat;
