/**
 * NACHA SEC code ENR — Automated Enrollment Entry.
 *
 * <p>Enrollment notification<br>
 * Use case: Federal enrollment<br>
 * Consumer/Corporate: CORPORATE<br>
 * Requires authorization: false<br>
 * Allows return: false
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.enr;
