/**
 * SWIFT MT740 — Authorisation to Reimburse.
 *
 * <p>Reimbursement authorisation
 *
 * <p>Category: 7<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt740;
