/**
 * SWIFT MT330 — Call/Notice Loan/Deposit Confirmation.
 *
 * <p>Call money trade confirmation
 *
 * <p>Category: 3<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt330;
