/**
 * NACHA SEC code TEL — Telephone-Initiated Entry.
 *
 * <p>Phone-authorized debit<br>
 * Use case: Phone order<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: true<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.tel;
