/**
 * NACHA SEC code ARC — Accounts Receivable Entry.
 *
 * <p>Mailed check converted<br>
 * Use case: AR conversion<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: true<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.arc;
