/**
 * SWIFT MT941 — Balance Report.
 *
 * <p>Balance report
 *
 * <p>Category: 9<br>
 * Payment: false<br>
 * Statement: true<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt941;
