/**
 * SWIFT MT710 — Advice of a Third Bank's Documentary Credit.
 *
 * <p>Third-bank LC advice
 *
 * <p>Category: 7<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt710;
