/**
 * CommercialChecking delivered via the Third-Party API channel (API).
 *
 * <p>Channel type: DIGITAL<br>
 * Device class: API_CLIENT<br>
 * Auth strength: OAUTH2<br>
 * Target latency: 150ms
 *
 * <p>Generated by {@code ChannelVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.channel.commercialchecking.api;
