/**
 * StandardSavings delivered via the Web Banking channel (WEB).
 *
 * <p>Channel type: DIGITAL<br>
 * Device class: BROWSER<br>
 * Auth strength: PASSWORD_2FA<br>
 * Target latency: 500ms
 *
 * <p>Generated by {@code ChannelVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.channel.standardsavings.web;
