/**
 * NACHA SEC code XCK — Destroyed Check Entry.
 *
 * <p>Lost or destroyed check<br>
 * Use case: Destroyed check<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: false<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.xck;
