/**
 * TeenChecking as offered under the Omnibank brand.
 *
 * <p>Primary segment: UNIVERSAL<br>
 * Digital-only: false<br>
 * Premium: false<br>
 * Founded: 1987
 *
 * <p>Generated by {@code BrandVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.brand.teenchecking.omnibank;
