/**
 * SWIFT MT202COV — Cover Payment.
 *
 * <p>Cover payment for MT103
 *
 * <p>Category: 2<br>
 * Payment: true<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt202cov;
