/**
 * VacationClub as offered under the OmniDirect brand.
 *
 * <p>Primary segment: DIGITAL_NATIVE<br>
 * Digital-only: true<br>
 * Premium: false<br>
 * Founded: 2015
 *
 * <p>Generated by {@code BrandVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.brand.vacationclub.omnidirect;
