/**
 * SWIFT MT700 — Issue of a Documentary Credit.
 *
 * <p>Documentary LC issuance
 *
 * <p>Category: 7<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt700;
