/**
 * SWIFT MT102 — Multiple Customer Credit Transfer.
 *
 * <p>Bulk customer transfers
 *
 * <p>Category: 1<br>
 * Payment: true<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt102;
