/**
 * NACHA SEC code TRC — Truncated Entry.
 *
 * <p>Truncated check<br>
 * Use case: Check truncation<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: false<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.trc;
