/**
 * SWIFT MT203 — Multiple FI Transfer For Own Account.
 *
 * <p>Multiple own-account bank transfers
 *
 * <p>Category: 2<br>
 * Payment: true<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt203;
