/**
 * SWIFT MT450 — Cash Letter Credit Advice.
 *
 * <p>Cash letter credit
 *
 * <p>Category: 4<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt450;
