/**
 * BasicChecking as offered under the StartupFi brand.
 *
 * <p>Primary segment: SMALL_BUSINESS<br>
 * Digital-only: true<br>
 * Premium: false<br>
 * Founded: 2018
 *
 * <p>Generated by {@code BrandVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.brand.basicchecking.startupfi;
