/**
 * NACHA SEC code COR — Notification of Change.
 *
 * <p>Correction notification<br>
 * Use case: Update receiver info<br>
 * Consumer/Corporate: CORPORATE<br>
 * Requires authorization: false<br>
 * Allows return: false
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.cor;
