/**
 * SWIFT MT340 — Forward Rate Agreement Confirmation.
 *
 * <p>FRA confirmation
 *
 * <p>Category: 3<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt340;
