/**
 * SWIFT MT705 — Pre-Advice of a Documentary Credit.
 *
 * <p>LC pre-advice
 *
 * <p>Category: 7<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt705;
