/**
 * SWIFT MT420 — Tracer.
 *
 * <p>Collection tracer
 *
 * <p>Category: 4<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt420;
