/**
 * NACHA SEC code PPD — Prearranged Payment and Deposit.
 *
 * <p>Direct deposit or recurring debit<br>
 * Use case: Payroll and recurring bills<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: true<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.ppd;
