/**
 * NACHA SEC code POP — Point-of-Purchase Entry.
 *
 * <p>Check converted at register<br>
 * Use case: Retail check conversion<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: true<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.pop;
