/**
 * SWIFT MT750 — Advice of Discrepancy.
 *
 * <p>LC document discrepancy
 *
 * <p>Category: 7<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt750;
