/**
 * SmallBizChecking delivered via the Mobile App channel (MOBILE).
 *
 * <p>Channel type: DIGITAL<br>
 * Device class: SMARTPHONE<br>
 * Auth strength: BIOMETRIC<br>
 * Target latency: 300ms
 *
 * <p>Generated by {@code ChannelVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.channel.smallbizchecking.mobile;
