/**
 * VeteranChecking as offered under the SilverBank brand.
 *
 * <p>Primary segment: SENIOR<br>
 * Digital-only: false<br>
 * Premium: false<br>
 * Founded: 2002
 *
 * <p>Generated by {@code BrandVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.brand.veteranchecking.silverbank;
