/**
 * NACHA SEC code CTX — Corporate Trade Exchange.
 *
 * <p>Structured remittance payment<br>
 * Use case: B2B with remittance<br>
 * Consumer/Corporate: CORPORATE<br>
 * Requires authorization: true<br>
 * Allows return: true (2-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.ctx;
