/**
 * SWIFT MT720 — Transfer of a Documentary Credit.
 *
 * <p>LC transfer
 *
 * <p>Category: 7<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt720;
