/**
 * NACHA SEC code BOC — Back Office Conversion.
 *
 * <p>Check converted in back office<br>
 * Use case: Lockbox conversion<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: true<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.boc;
