/**
 * NACHA SEC code DNE — Death Notification Entry.
 *
 * <p>Government death notification<br>
 * Use case: SSA death notification<br>
 * Consumer/Corporate: CORPORATE<br>
 * Requires authorization: false<br>
 * Allows return: false
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.dne;
