/**
 * SWIFT MT707 — Amendment to a Documentary Credit.
 *
 * <p>LC amendment
 *
 * <p>Category: 7<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt707;
