/**
 * SWIFT MT422 — Advice of Fate and Request for Instructions.
 *
 * <p>Fate advice
 *
 * <p>Category: 4<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt422;
