/**
 * EssentialChecking regional fork for South Dakota (SD), MIDWEST.
 *
 * <p>Generated by {@code RegionalForkGenerator}. State-level
 * overrides include Reg DD disclosure variations, escheatment rules,
 * state tax withholding for retirement products, and FDIC regional
 * examiner assignment (KANSAS_CITY).
 */
package com.omnibank.regional.essentialchecking.sd;
