/**
 * BasicChecking regional fork for West Virginia (WV), SOUTH.
 *
 * <p>Generated by {@code RegionalForkGenerator}. State-level
 * overrides include Reg DD disclosure variations, escheatment rules,
 * state tax withholding for retirement products, and FDIC regional
 * examiner assignment (ATLANTA).
 */
package com.omnibank.regional.basicchecking.wv;
