/**
 * TeenChecking delivered via the Interactive Voice Response channel (IVR).
 *
 * <p>Channel type: VOICE<br>
 * Device class: PHONE<br>
 * Auth strength: ACCOUNT_PIN<br>
 * Target latency: 600ms
 *
 * <p>Generated by {@code ChannelVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.channel.teenchecking.ivr;
