/**
 * SWIFT MT400 — Advice of Payment.
 *
 * <p>Collection payment advice
 *
 * <p>Category: 4<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt400;
