/**
 * SWIFT MT701 — Issue of a Documentary Credit (Extension).
 *
 * <p>LC extension
 *
 * <p>Category: 7<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt701;
