/**
 * StandardSavings as offered under the FutureBank brand.
 *
 * <p>Primary segment: FAMILY<br>
 * Digital-only: false<br>
 * Premium: false<br>
 * Founded: 2009
 *
 * <p>Generated by {@code BrandVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.brand.standardsavings.futurebank;
