/**
 * SWIFT MT360 — Single Currency Interest Rate Swap.
 *
 * <p>IRS confirmation
 *
 * <p>Category: 3<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt360;
