package com.omnibank.swift.mt107;

import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Auto-generated scenario tests for the Mt107 SWIFT message handler.
 * Generated by {@code com.aibench.codegen.SwiftScenarioTestGenerator}.
 *
 * <p>Coverage: handler counters, parser-input handling, validator
 * findings shape, routing decisions, message-type classification,
 * intra-group BIC detection, high-value-priority override.
 */
class Mt107ScenarioMatrixTest {

    private static final String VALID_BIC_BLOCK =
            "sender=OMNIUS33XXX\nreceiver=CHASUS33XXX\n:20:REF\n";

    private final Mt107Handler handler = new Mt107Handler();
    private final Mt107Parser parser = new Mt107Parser();
    private final Mt107Validator validator = new Mt107Validator();
    private final Mt107RoutingRules routing = new Mt107RoutingRules();

    @Test
    void handler_null_input_throws_npe() {
        assertThatThrownBy(() -> handler.handle(null))
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void handler_empty_input_is_processed_but_rejected() {
        var result = handler.handle("");
        assertThat(result).isNotNull();
        assertThat(result.accepted()).isFalse();
    }

    @Test
    void handler_counters_increment_per_invocation() {
        long before = handler.processedCount();
        handler.handle("");
        handler.handle("");
        handler.handle("");
        assertThat(handler.processedCount() - before).isEqualTo(3);
    }

    @Test
    void handler_accepted_plus_rejected_equals_processed() {
        handler.handle("");
        handler.handle(":20:REF1\nsender=OMNIUS33XXX\nreceiver=CHASUS33XXX\n");
        assertThat(handler.acceptedCount() + handler.rejectedCount())
                .isEqualTo(handler.processedCount());
    }

    @Test
    void parser_null_throws_npe() {
        assertThatThrownBy(() -> parser.parse(null))
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void parser_minimal_valid_input_returns_message_with_required_fields() {
        var msg = parser.parse(VALID_BIC_BLOCK);
        assertThat(msg).isNotNull();
        assertThat(msg.senderBic()).isNotBlank();
        assertThat(msg.receiverBic()).isNotBlank();
    }

    @Test
    void parser_well_formed_message_round_trips_reference() {
        String block = "sender=OMNIUS33XXX\n"
                + "receiver=CHASUS33XXX\n"
                + ":20:TESTREF1\n"
                + ":32A:260416USD1000,00\n"
                + ":59:BENEFICIARY\n"
                + ":70:DETAILS\n";
        var msg = parser.parse(block);
        assertThat(msg.messageReference()).isEqualTo("TESTREF1");
    }

    @Test
    void validator_null_message_throws_npe() {
        assertThatThrownBy(() -> validator.validate(null))
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void validator_returns_result_with_non_null_findings_list() {
        var msg = parser.parse(VALID_BIC_BLOCK);
        var result = validator.validate(msg);
        assertThat(result).isNotNull();
        assertThat(result.findings()).isNotNull();
    }

    @Test
    void validator_isvalid_consistent_with_haserrors() {
        var msg = parser.parse(":20:OK\nsender=OMNIUS33XXX\nreceiver=CHASUS33XXX\n");
        var result = validator.validate(msg);
        assertThat(result.isValid()).isEqualTo(!result.hasErrors());
    }

    @Test
    void routing_returns_non_null_destination_for_any_message() {
        var msg = parser.parse("sender=OMNIUS33XXX\nreceiver=CHASUS33XXX\n");
        assertThat(routing.routeFor(msg)).isNotNull();
    }

    @Test
    void routing_throws_npe_for_null_message() {
        assertThatThrownBy(() -> routing.routeFor(null))
                .isInstanceOf(NullPointerException.class);
    }

    @Test
    void routing_intra_group_recognizes_bank_prefix() {
        assertThat(routing.isIntraGroup("OMNIUS33XXX")).isTrue();
    }

    @Test
    void routing_intra_group_null_bic_is_not_intra_group() {
        assertThat(routing.isIntraGroup(null)).isFalse();
    }

    @Test
    void routing_intra_group_external_bic_is_not_intra_group() {
        assertThat(routing.isIntraGroup("CHASUS33XXX")).isFalse();
    }

    @Test
    void routing_high_value_amount_returns_priority_queue_override() {
        String block = "sender=OMNIUS33XXX\n"
                + "receiver=CHASUS33XXX\n"
                + ":20:BIG\n"
                + ":32A:260416USD20000000,00\n"
                + ":59:BENEFICIARY\n";
        var msg = parser.parse(block);
        assertThat(routing.priorityQueueOverride(msg))
                .isEqualTo("HIGH_VALUE_REVIEW_QUEUE");
    }

    @Test
    void routing_low_value_amount_returns_null_override() {
        String block = "sender=OMNIUS33XXX\n"
                + "receiver=CHASUS33XXX\n"
                + ":20:SMALL\n"
                + ":32A:260416USD100,00\n"
                + ":59:BENEFICIARY\n";
        var msg = parser.parse(block);
        assertThat(routing.priorityQueueOverride(msg)).isNull();
    }

    @Test
    void message_type_label_is_present() {
        var msg = parser.parse(VALID_BIC_BLOCK);
        assertThat(msg.messageType()).isNotBlank();
    }

    @Test
    void message_classification_predicates_are_booleans() {
        var msg = parser.parse(VALID_BIC_BLOCK);
        // Just call them to ensure no NPE; results vary by MT type.
        msg.isPayment();
        msg.isStatement();
        msg.requiresSettlement();
    }

    @Test
    void destination_enum_includes_dead_letter_fallback() {
        assertThat(Mt107RoutingRules.Destination.values())
                .contains(Mt107RoutingRules.Destination.DEAD_LETTER_QUEUE);
    }
}
