/**
 * TeenChecking delivered via the Phone Banking channel (CALL_CENTER).
 *
 * <p>Channel type: VOICE<br>
 * Device class: PHONE<br>
 * Auth strength: VOICE_VERIFICATION<br>
 * Target latency: 800ms
 *
 * <p>Generated by {@code ChannelVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.channel.teenchecking.call_center;
