/**
 * SWIFT MT205 — Financial Institution Transfer Execution.
 *
 * <p>Bank transfer execution
 *
 * <p>Category: 2<br>
 * Payment: true<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt205;
