/**
 * SWIFT MT200 — Financial Institution Transfer For Own Account.
 *
 * <p>Bank-to-bank own-account transfer
 *
 * <p>Category: 2<br>
 * Payment: true<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt200;
