/**
 * SWIFT MT304 — Advice/Instruction of a Third Party Deal.
 *
 * <p>FX third party deal
 *
 * <p>Category: 3<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt304;
