/**
 * DigitalOnlyChecking regional fork for Alaska (AK), WEST.
 *
 * <p>Generated by {@code RegionalForkGenerator}. State-level
 * overrides include Reg DD disclosure variations, escheatment rules,
 * state tax withholding for retirement products, and FDIC regional
 * examiner assignment (SAN_FRANCISCO).
 */
package com.omnibank.regional.digitalonlychecking.ak;
