package com.omnibank.brand.christmasclub.bluewaterbank;

import java.math.BigDecimal;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Auto-generated brand-scenario tests for the ChristmasClubBluewaterbank brand fork.
 * Generated by {@code com.aibench.codegen.BrandScenarioTestGenerator}.
 *
 * <p>Coverage: brand identity invariants, age-bound checks,
 * marketing copy presence, pricing-override math, onboarding
 * step ordering, and customer-communication footers.
 */
class ChristmasClubBluewaterbankScenarioMatrixTest {

    @Test
    void brand_profile_identity_fields_present() {
        var p = new ChristmasClubBluewaterbankBrandProfile();
        assertThat(p.brandCode()).isNotBlank();
        assertThat(p.displayName()).isNotBlank();
        assertThat(p.tagline()).isNotBlank();
    }

    @Test
    void brand_primary_color_is_hex_format() {
        var p = new ChristmasClubBluewaterbankBrandProfile();
        assertThat(p.primaryColor()).startsWith("#");
        assertThat(p.primaryColor().length()).isIn(4, 7, 9);
    }

    @Test
    void brand_minimum_age_is_realistic() {
        var p = new ChristmasClubBluewaterbankBrandProfile();
        assertThat(p.minimumAge()).isBetween(0, 70);
    }

    @Test
    void brand_founded_year_is_in_modern_banking_era() {
        var p = new ChristmasClubBluewaterbankBrandProfile();
        assertThat(p.brandFounded()).isBetween(1850, 2030);
    }

    @Test
    void brand_age_in_years_is_consistent_with_founded() {
        var p = new ChristmasClubBluewaterbankBrandProfile();
        int years = p.ageInYears(2026);
        assertThat(years).isEqualTo(2026 - p.brandFounded());
    }

    @Test
    void brand_heritage_predicate_consistent_with_age() {
        var p = new ChristmasClubBluewaterbankBrandProfile();
        assertThat(p.isHeritageBrand(2026))
                .isEqualTo(p.ageInYears(2026) >= 50);
    }

    @Test
    void brand_value_statements_are_nonempty() {
        var p = new ChristmasClubBluewaterbankBrandProfile();
        assertThat(p.brandValueStatements()).isNotEmpty();
        for (String s : p.brandValueStatements()) {
            assertThat(s).isNotBlank();
        }
    }

    @Test
    void brand_promise_headline_is_present() {
        var p = new ChristmasClubBluewaterbankBrandProfile();
        assertThat(p.brandPromiseHeadline()).isNotBlank();
    }

    @Test
    void marketing_copy_hero_headline_present() {
        var m = new ChristmasClubBluewaterbankMarketingCopy();
        assertThat(m.heroHeadline()).isNotBlank();
        assertThat(m.subheadline()).isNotBlank();
    }

    @Test
    void marketing_call_to_action_verb_is_concise() {
        var m = new ChristmasClubBluewaterbankMarketingCopy();
        assertThat(m.callToActionVerb()).isNotBlank();
        assertThat(m.callToActionVerb().length()).isLessThanOrEqualTo(40);
    }

    @Test
    void marketing_footer_legal_is_present() {
        var m = new ChristmasClubBluewaterbankMarketingCopy();
        assertThat(m.footerLegal()).isNotBlank();
    }

    @Test
    void pricing_apy_bonus_is_finite_bps() {
        var po = new ChristmasClubBluewaterbankPricingOverride();
        assertThat(po.apyBonusBps()).isNotNull();
        // BPS bonuses across our brand catalog are within ±200bps.
        assertThat(po.apyBonusBps().abs())
                .isLessThanOrEqualTo(new BigDecimal("200"));
    }

    @Test
    void pricing_adjust_apy_is_idempotent_at_zero_bonus_when_bonus_zero() {
        var po = new ChristmasClubBluewaterbankPricingOverride();
        var nationalApy = new BigDecimal("0.0300");
        var adjusted = po.adjustApy(nationalApy);
        if (po.apyBonusBps().signum() == 0) {
            assertThat(adjusted).isEqualByComparingTo(nationalApy);
        }
    }

    @Test
    void pricing_adjust_monthly_fee_returns_value() {
        var po = new ChristmasClubBluewaterbankPricingOverride();
        var national = new BigDecimal("12.00");
        var adjusted = po.adjustMonthlyFee(national);
        assertThat(adjusted).isNotNull();
        assertThat(adjusted.signum()).isGreaterThanOrEqualTo(0);
    }

    @Test
    void pricing_promotional_flag_is_a_boolean() {
        var po = new ChristmasClubBluewaterbankPricingOverride();
        // Boolean predicate, must not throw.
        boolean unused = po.isPromotionalRateActive();
        assertThat(unused).isIn(true, false);
    }

    @Test
    void onboarding_flow_has_at_least_one_step() {
        var of = new ChristmasClubBluewaterbankOnboardingFlow();
        assertThat(of.stepCount()).isGreaterThanOrEqualTo(1);
        assertThat(of.steps()).hasSize(of.stepCount());
    }

    @Test
    void onboarding_steps_are_sequenced_uniquely() {
        var of = new ChristmasClubBluewaterbankOnboardingFlow();
        var seen = new java.util.HashSet<Integer>();
        for (var step : of.steps()) {
            assertThat(step.code()).isNotBlank();
            assertThat(step.label()).isNotBlank();
            assertThat(step.sequenceNumber()).isGreaterThanOrEqualTo(0);
            assertThat(seen.add(step.sequenceNumber()))
                    .as("sequence " + step.sequenceNumber() + " was duplicated")
                    .isTrue();
        }
    }

    @Test
    void onboarding_estimated_minutes_is_reasonable() {
        var of = new ChristmasClubBluewaterbankOnboardingFlow();
        assertThat(of.estimatedMinutes()).isBetween(1L, 120L);
    }

    @Test
    void communication_sender_address_looks_like_email() {
        var c = new ChristmasClubBluewaterbankCustomerCommunication();
        assertThat(c.senderFromAddress()).contains("@");
    }

    @Test
    void communication_signature_block_present_and_unsubscribe_footer_legal() {
        var c = new ChristmasClubBluewaterbankCustomerCommunication();
        assertThat(c.signatureBlock()).isNotBlank();
        assertThat(c.unsubscribeFooter()).isNotBlank();
    }
}
