/**
 * NACHA SEC code SHR — Shared Network Transaction.
 *
 * <p>Shared network POS<br>
 * Use case: Shared POS network<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: true<br>
 * Allows return: false
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.shr;
