/**
 * NACHA SEC code CIE — Customer-Initiated Entry.
 *
 * <p>Bill payment sent by customer<br>
 * Use case: Consumer bill payment<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: true<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.cie;
