/**
 * SWIFT MT202 — General Financial Institution Transfer.
 *
 * <p>Bank-to-bank general transfer
 *
 * <p>Category: 2<br>
 * Payment: true<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt202;
