package com.omnibank.regional.basicchecking.sd;

import java.math.BigDecimal;
import java.time.YearMonth;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Auto-generated scenario-matrix tests for the BasicCheckingSD jurisdictional
 * fork. Generated by {@code com.aibench.codegen.RegionalScenarioTestGenerator}
 * from the public APIs of the existing {@link BasicCheckingSDProfile},
 * {@link BasicCheckingSDRateTable}, {@link BasicCheckingSDDisclosures},
 * {@link BasicCheckingSDRegulatoryFilings}, and {@link BasicCheckingSDBranchIntegration}.
 *
 * <p>Tests here cover boundary scenarios that the hand-written
 * {@code BasicCheckingSDProfileTest} does not exercise: rate-band tier
 * monotonicity, sales-tax rounding precision, channel availability
 * vs. profile flags, multi-quarter regulatory filings.
 */
class BasicCheckingSDScenarioMatrixTest {

    @Test
    void profile_state_code_is_two_letters() {
        var p = new BasicCheckingSDProfile();
        assertThat(p.stateCode()).hasSize(2);
        assertThat(p.stateName()).isNotBlank();
    }

    @Test
    void profile_region_is_one_of_the_four_us_regions() {
        var p = new BasicCheckingSDProfile();
        assertThat(p.region()).isIn("WEST", "MIDWEST", "SOUTH", "NORTHEAST");
    }

    @Test
    void profile_sales_tax_rate_is_within_us_range() {
        var p = new BasicCheckingSDProfile();
        // No US state has > 11% combined tax; treat the profile rate
        // as state-only so an upper bound of 12% is comfortably above.
        assertThat(p.salesTaxRate()).isGreaterThanOrEqualTo(BigDecimal.ZERO);
        assertThat(p.salesTaxRate()).isLessThanOrEqualTo(new BigDecimal("0.12"));
    }

    @Test
    void profile_escheatment_window_is_realistic() {
        var p = new BasicCheckingSDProfile();
        assertThat(p.escheatmentDormancyYears()).isBetween(1, 10);
    }

    @Test
    void profile_no_sales_tax_predicate_is_consistent() {
        var p = new BasicCheckingSDProfile();
        assertThat(p.isNoSalesTaxState())
                .isEqualTo(p.salesTaxRate().signum() == 0);
    }

    @Test
    void apply_state_fee_tax_zero_in_zero_out() {
        var p = new BasicCheckingSDProfile();
        assertThat(p.applyStateFeeTax(BigDecimal.ZERO))
                .isEqualByComparingTo(BigDecimal.ZERO);
    }

    @Test
    void apply_state_fee_tax_preserves_two_decimals() {
        var p = new BasicCheckingSDProfile();
        var taxed = p.applyStateFeeTax(new BigDecimal("12.34"));
        assertThat(taxed.scale()).isEqualTo(2);
    }

    @Test
    void apply_state_fee_tax_is_monotonic_in_input() {
        var p = new BasicCheckingSDProfile();
        var lo = p.applyStateFeeTax(new BigDecimal("5.00"));
        var hi = p.applyStateFeeTax(new BigDecimal("50.00"));
        assertThat(hi).isGreaterThanOrEqualTo(lo);
    }

    @Test
    void rate_table_band_count_is_at_least_three() {
        var rt = new BasicCheckingSDRateTable();
        assertThat(rt.bands().size()).isGreaterThanOrEqualTo(3);
    }

    @Test
    void rate_table_apys_are_non_negative_across_buckets() {
        var rt = new BasicCheckingSDRateTable();
        for (String bal : new String[]{"0", "100", "1000", "10000", "100000", "5000000"}) {
            assertThat(rt.apyFor(new BigDecimal(bal)).signum())
                    .as("balance " + bal)
                    .isGreaterThanOrEqualTo(0);
        }
    }

    @Test
    void rate_table_is_monotonically_non_decreasing() {
        var rt = new BasicCheckingSDRateTable();
        var prev = rt.apyFor(BigDecimal.ZERO);
        for (String bal : new String[]{"500", "5000", "50000", "500000"}) {
            var cur = rt.apyFor(new BigDecimal(bal));
            assertThat(cur).as("balance " + bal).isGreaterThanOrEqualTo(prev);
            prev = cur;
        }
    }

    @Test
    void rate_table_top_tier_matches_max_observed_apy() {
        var rt = new BasicCheckingSDRateTable();
        var top = rt.topTierApy();
        for (String bal : new String[]{"100", "10000", "1000000"}) {
            assertThat(top).isGreaterThanOrEqualTo(rt.apyFor(new BigDecimal(bal)));
        }
    }

    @Test
    void rate_sheet_reference_is_traceable() {
        var rt = new BasicCheckingSDRateTable();
        assertThat(rt.rateSheetRef()).isNotBlank();
        assertThat(rt.effectiveFrom().getYear()).isBetween(2020, 2030);
    }

    @Test
    void disclosures_full_supplement_contains_state_name() {
        var p = new BasicCheckingSDProfile();
        var d = new BasicCheckingSDDisclosures();
        assertThat(d.renderFullSupplement()).contains(p.stateName());
    }

    @Test
    void disclosures_supplement_is_not_blank() {
        var d = new BasicCheckingSDDisclosures();
        assertThat(d.renderFullSupplement()).isNotBlank();
    }

    @Test
    void regulatory_filings_all_quarters_produce_output() {
        var f = new BasicCheckingSDRegulatoryFilings();
        for (int month : new int[]{3, 6, 9, 12}) {
            assertThat(f.quarterlyFilings(YearMonth.of(2026, month)))
                    .as("quarter ending month " + month)
                    .isNotEmpty();
        }
    }

    @Test
    void branch_integration_web_and_mobile_always_active() {
        var b = new BasicCheckingSDBranchIntegration();
        assertThat(b.channelActive("WEB")).isTrue();
        assertThat(b.channelActive("MOBILE")).isTrue();
    }

    @Test
    void branch_integration_unknown_channel_is_inactive() {
        var b = new BasicCheckingSDBranchIntegration();
        assertThat(b.channelActive("CARRIER_PIGEON")).isFalse();
    }

    @Test
    void branch_integration_atm_is_active_in_every_state() {
        var b = new BasicCheckingSDBranchIntegration();
        assertThat(b.channelActive("ATM")).isTrue();
    }

    @Test
    void state_authority_name_is_present_and_nontrivial() {
        var p = new BasicCheckingSDProfile();
        assertThat(p.stateBankingAuthority()).isNotBlank();
        assertThat(p.stateBankingAuthority().length()).isGreaterThanOrEqualTo(8);
    }
}
