/**
 * StandardSavings regional fork for New York (NY), NORTHEAST.
 *
 * <p>Generated by {@code RegionalForkGenerator}. State-level
 * overrides include Reg DD disclosure variations, escheatment rules,
 * state tax withholding for retirement products, and FDIC regional
 * examiner assignment (NEW_YORK).
 */
package com.omnibank.regional.standardsavings.ny;
