/**
 * SWIFT MT320 — Fixed Loan/Deposit Confirmation.
 *
 * <p>Loan/deposit trade confirmation
 *
 * <p>Category: 3<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt320;
