/**
 * NACHA SEC code ADV — Automated Accounting Advice.
 *
 * <p>Non-monetary advice<br>
 * Use case: Accounting advice only<br>
 * Consumer/Corporate: CORPORATE<br>
 * Requires authorization: false<br>
 * Allows return: false
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.adv;
