/**
 * CdLadder24Month as offered under the BlueWater Community Bank brand.
 *
 * <p>Primary segment: COMMUNITY<br>
 * Digital-only: false<br>
 * Premium: false<br>
 * Founded: 1971
 *
 * <p>Generated by {@code BrandVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.brand.cdladder24month.bluewaterbank;
