/**
 * SWIFT MT940 — Customer Statement Message.
 *
 * <p>Customer account statement
 *
 * <p>Category: 9<br>
 * Payment: false<br>
 * Statement: true<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt940;
