/**
 * BasicChecking regional fork for Arkansas (AR), SOUTH.
 *
 * <p>Generated by {@code RegionalForkGenerator}. State-level
 * overrides include Reg DD disclosure variations, escheatment rules,
 * state tax withholding for retirement products, and FDIC regional
 * examiner assignment (DALLAS).
 */
package com.omnibank.regional.basicchecking.ar;
