/**
 * PremierMoneyMarket as offered under the Legacy Trust brand.
 *
 * <p>Primary segment: HIGH_NET_WORTH<br>
 * Digital-only: false<br>
 * Premium: true<br>
 * Founded: 1907
 *
 * <p>Generated by {@code BrandVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.brand.premiermoneymarket.legacytrust;
