/**
 * HighYieldSavings regional fork for Wyoming (WY), WEST.
 *
 * <p>Generated by {@code RegionalForkGenerator}. State-level
 * overrides include Reg DD disclosure variations, escheatment rules,
 * state tax withholding for retirement products, and FDIC regional
 * examiner assignment (KANSAS_CITY).
 */
package com.omnibank.regional.highyieldsavings.wy;
