/**
 * SWIFT MT103 — Single Customer Credit Transfer.
 *
 * <p>Single customer credit transfer
 *
 * <p>Category: 1<br>
 * Payment: true<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt103;
