/**
 * NACHA SEC code TRX — Truncated Check Exchange.
 *
 * <p>Check exchange truncation<br>
 * Use case: Check exchange<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: false<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.trx;
