/**
 * SWIFT MT107 — General Direct Debit.
 *
 * <p>General direct debit message
 *
 * <p>Category: 1<br>
 * Payment: true<br>
 * Statement: false<br>
 * Requires settlement: true
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt107;
