/**
 * NACHA SEC code CCD — Cash Concentration or Disbursement.
 *
 * <p>Corporate cash management<br>
 * Use case: Cash concentration<br>
 * Consumer/Corporate: CORPORATE<br>
 * Requires authorization: true<br>
 * Allows return: true (2-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.ccd;
