/**
 * NACHA SEC code WEB — Internet-Initiated/Mobile Entry.
 *
 * <p>Consumer online payment<br>
 * Use case: Online bill pay<br>
 * Consumer/Corporate: CONSUMER<br>
 * Requires authorization: true<br>
 * Allows return: true (60-day window)
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.web;
