/**
 * EssentialChecking delivered via the Branch Teller channel (BRANCH).
 *
 * <p>Channel type: PHYSICAL<br>
 * Device class: TERMINAL<br>
 * Auth strength: ID_IN_PERSON<br>
 * Target latency: 1000ms
 *
 * <p>Generated by {@code ChannelVariantGenerator}. Do not hand-edit.
 */
package com.omnibank.channel.essentialchecking.branch;
