/**
 * NACHA SEC code ACK — ACH Acknowledgement.
 *
 * <p>Prenote acknowledgement<br>
 * Use case: Prenote ack<br>
 * Consumer/Corporate: CORPORATE<br>
 * Requires authorization: false<br>
 * Allows return: false
 *
 * <p>Generated by {@code NachaSecCodeGenerator}. Do not hand-edit.
 */
package com.omnibank.nacha.ack;
