/**
 * SWIFT MT412 — Advice of Acceptance.
 *
 * <p>Draft acceptance advice
 *
 * <p>Category: 4<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt412;
