/**
 * SWIFT MT290 — Advice of Charges Interest and Other.
 *
 * <p>Fee and charge advice
 *
 * <p>Category: 2<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt290;
