/**
 * SWIFT MT110 — Advice of Cheque.
 *
 * <p>Advice of cheque issued
 *
 * <p>Category: 1<br>
 * Payment: true<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt110;
