/**
 * SWIFT MT210 — Notice to Receive.
 *
 * <p>Pre-advice of incoming funds
 *
 * <p>Category: 2<br>
 * Payment: false<br>
 * Statement: false<br>
 * Requires settlement: false
 *
 * <p>Generated by {@code SwiftMessageHandlerGenerator}. Do not hand-edit.
 */
package com.omnibank.swift.mt210;
